#!/usr/bin/env bash
# SPDX-FileCopyrightText: (c) 2017 Anton Babenko
# SPDX-FileCopyrightText: (c) 2020 Begley Brothers Inc. <BegleyBrothers@gmail.com>
# SPDX-License-Identifier: Apache-2.0 OR MIT

if [[ ${DEBUG-} =~ ^1|y|yes|true$ ]]; then
  # Take stdout and stderr from this script. 
  # Redirect to the logger command, which sends to syslog.
  # Adding `-s` echoes to stderr - however profile is run by non-interactive
  # terminals and any noise from them breaks sftp and scp.
  # See OpenSSH FAQ note below.
  # So when debugging we actually want to log lots but be 'silent' wrt to the
  # terminal.
  exec 1> >(logger -t $(basename $0)) 2>&1
  set -o xtrace       # Trace the execution of the script (debug)
fi
set -o errexit

declare -a paths
declare -a tfvars_files

index=0
tfidx=0

## Turn off exit-on-error because...
#
set +o errexit
#
# ... the `ls` command errors when the changeset is
# only deleted files.
#
staged_files=($(git diff-index --cached --name-only HEAD | xargs ls -1 2>/dev/null)) || true
set -o errexit

for file_with_path in "${staged_files[@]}"; do
  file_with_path="${file_with_path// /__REPLACED__SPACE__}"

  paths[index]=$(dirname "$file_with_path")

  if [ ${file_with_path: -3} == ".rs" ]
  then
    wip_files+=("$file_with_path")
    let "rbidx+=1"
  fi

  let "index+=1"
done

## Run only on the files we need to:
#
# `rustfmt ... <file>`
#
# We `--skip-children` to avoid checking submodules of a module.
# Those files may be uncommitted but cause the check to fail.
#
for wip_file in "${wip_files[@]}"; do
  wip_file="${wip_file//__REPLACED__SPACE__/ }"
  rustfmt --skip-children --force --write-mode overwrite "${wip_file}" 2>/dev/null || true
done
